### ISSUE TITLE
example does not work out of the box

### ISSUE THREAD

**Issue by migounette** [joyent/node-snmpjs#19]
windows 8.1 - snmpget from net.smnp project

I didn't succeed to run the example from the readme.md

```
    agent.request({ oid: '.1.3.6.1.2.1.1.5', handler: function (prq) {
         var nodename = os.hostname();
         var val = snmp.data.createData({ type: 'OctetString', value: nodename });
         snmp.provider.readOnlyScalar(prq, val);
} });   
```

I looked into the code and I found this:

prq.instance is always undefined so it returns noSuchInstance whereas the handler is correctly registered. So I comment this section and up to the else keyword and it works !

agent.js:197

```
        if (!prq.instance || decor._scalar &&
            (prq.instance.length > 1 || prq.instance[0] != 0)) {
            handler = [ function _getset_nsihandler(pr) {
                var rsd = data.createData({
                    type: 'Null',
                    value: data.noSuchInstance
                });
                var rsvb = varbind.createVarbind({
                    oid: pr.oid, data: rsd });
                pr.done(rsvb);
            } ];
        } else {
            debugger;
            if (prq.op == PDU.SetRequest)
                prq._value = vb.data;
            handler = decor._handler;
        }
```

Any idea ?

**Comment by messeiry** [comment]
i have been trying as well to create a client to set OIDs after launching an agent but its donot work. i tried to use thirdparty like snmpset command but it always return the original value created when launching the agent.

here is my code: 
`// to kill a process running in a port :
// sudo kill`sudo lsof -t -i:161`
/*
 snmpget -v 2c -c any localhost:5000 .1.3.6.1.2.1.1.5.0
 iso.3.6.1.2.1.1.5.0 = STRING: "ubuntu"

 $ snmpset -v 2c -c any localhost:5000  .1.3.6.1.2.1.1.5.0 s "Editable"
 iso.3.6.1.2.1.1.5.0 = STRING: "ubuntu"

 $ snmpwalk -v 2c -c public localhost:5000

 */

var os = require('os');
var snmp = require('snmpjs');

var agent = snmp.createAgent();
agent.bind({ family: 'udp4', port: 5000 });

agent.request({ oid: '.1.3.6.1.2.1.1.5', handler: function (prq) {
    var nodename = os.hostname();
    var val = snmp.data.createData({ type: 'OctetString', value: nodename });

```
snmp.provider.readOnlyScalar(prq, val);
//snmp.provider.writableScalar(prq, val);
```

} });

`
