### ISSUE TITLE
lib/protocol/message.js refers to ../parser - Cannot find module '../parser'

### ISSUE THREAD

**Issue by sirmxanot** [joyent/node-snmpjs#226]
I believe that this code is trying to load a file in its parent directory named parser.js and this file is absent. If this is incorrect, what is the parser that this require is referring to?

**Comment by bahamat** [comment]
It should be generated at install time. Either `npm install snmpjs` or after you clone, run `npm install` in the root of the repository.

**Comment by sirmxanot** [comment]
Yes. That is the correct solution. Thank you.
